param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

$ErrorActionPreference = 'Stop'
$generated = @(
    'docs/ALL_MARKDOWN_INDEX.md',
    'docs/PROJECT_KNOWLEDGE_BUNDLE.md'
)

function Get-DocCategory([string]$Path) {
    $p = $Path.Replace('\','/')
    if ($p -eq 'AGENTS.md' -or $p -eq 'docs/README.md') { return 'ENTRYPOINT' }
    if ($p -match '^docs/(00_PRODUCT|10_ARCHITECTURE|20_GAME_SYSTEMS|30_UI_UX|40_TESTING|90_DECISIONS)/') { return 'CANONICAL' }
    if ($p -match '^docs/99_HISTORY/') { return 'HISTORICAL' }
    if ($p -match 'THIRD_PARTY_NOTICES') { return 'THIRD_PARTY' }
    if ($p -match '(^|/)(REVISION_TECNICA|AUDITORIA)|^docs/(FINANCE|STAFF|INTERACTION_)') { return 'TECHNICAL_EVIDENCE' }
    return 'SUPPORTING'
}

function Get-DocPriority([string]$Category) {
    switch ($Category) {
        'ENTRYPOINT' { return 0 }
        'CANONICAL' { return 10 }
        'SUPPORTING' { return 20 }
        'TECHNICAL_EVIDENCE' { return 30 }
        'HISTORICAL' { return 40 }
        'THIRD_PARTY' { return 50 }
    }
}

$paths = @(& git -C $RepoRoot ls-files) |
    Where-Object { $_.ToLowerInvariant().EndsWith('.md') -and ($_ -notin $generated) }

$entries = foreach ($path in $paths) {
    $full = Join-Path $RepoRoot $path
    if (-not (Test-Path $full)) { continue }
    $text = [IO.File]::ReadAllText($full)
    $firstHeading = ($text -split "`r?`n" | Where-Object { $_ -match '^#\s+' } | Select-Object -First 1)
    if ($firstHeading) { $title = $firstHeading -replace '^#\s+','' } else { $title = [IO.Path]::GetFileName($path) }
    $category = Get-DocCategory $path
    [pscustomobject]@{
        Path = $path.Replace('\','/')
        Category = $category
        Priority = Get-DocPriority $category
        Bytes = [Text.Encoding]::UTF8.GetByteCount($text)
        Lines = (($text -split "`r?`n").Count)
        Title = $title.Trim()
        Text = ([regex]::Replace($text, '[ \t]+(?=\r?$)', '', [Text.RegularExpressions.RegexOptions]::Multiline)).TrimEnd()
    }
}

$entries = @($entries | Sort-Object Priority, Path)
$utf8 = New-Object System.Text.UTF8Encoding($false)
$indexPath = Join-Path $RepoRoot 'docs\ALL_MARKDOWN_INDEX.md'
$bundlePath = Join-Path $RepoRoot 'docs\PROJECT_KNOWLEDGE_BUNDLE.md'

$index = New-Object System.Collections.Generic.List[string]
$index.Add('# Bistro Builder - Global Markdown Index')
$index.Add('')
$index.Add('Generated by Tools/BistroBuilder/RefreshMarkdownKnowledge.ps1.')
$index.Add('')
$index.Add("Source documents: $($entries.Count)")
$index.Add("UTF-8 bytes: $((($entries | Measure-Object Bytes -Sum).Sum))")
$index.Add('')
$index.Add('## Precedence')
$index.Add('ENTRYPOINT > CANONICAL > integrated code/contracts > SUPPORTING > TECHNICAL_EVIDENCE > HISTORICAL > THIRD_PARTY.')
$index.Add('')
$index.Add('| Category | Document | Title | Lines |')
$index.Add('|---|---|---|---:|')
foreach ($e in $entries) {
    $safeTitle = $e.Title.Replace('|','\|')
    $index.Add("| $($e.Category) | [$($e.Path)](../$($e.Path)) | $safeTitle | $($e.Lines) |")
}
$index.Add('')
$index.Add('## Maintenance rule')
$index.Add('When any source .md is added, moved, deleted, or changed, regenerate this index and the bundle before commit.')
[IO.File]::WriteAllText($indexPath, ($index -join "`n") + "`n", $utf8)

$bundle = New-Object System.Collections.Generic.List[string]
$bundle.Add('# Bistro Builder - Project Knowledge Bundle')
$bundle.Add('')
$bundle.Add('Generated from every tracked source .md in the repository.')
$bundle.Add('This is a single ingestion point for agents; original files remain authoritative.')

$bundle.Add('')
$bundle.Add('## Mandatory precedence')
$bundle.Add('1. ENTRYPOINT and CANONICAL.')
$bundle.Add('2. Integrated code and public contracts when they describe verified behavior.')
$bundle.Add('3. SUPPORTING and TECHNICAL_EVIDENCE.')
$bundle.Add('4. HISTORICAL and THIRD_PARTY only for context and traceability.')
$bundle.Add('')
$bundle.Add('Historical material never overrides a later canonical decision.')
$bundle.Add('')
foreach ($e in $entries) {
    $bundle.Add('---')
    $bundle.Add('')
    $bundle.Add("## SOURCE: $($e.Path)")
    $bundle.Add('')
    $bundle.Add("Category: $($e.Category)")
    $bundle.Add('')
    $bundle.Add($e.Text)
    $bundle.Add('')
}
[IO.File]::WriteAllText($bundlePath, (($bundle -join "`n").TrimEnd()) + "`n", $utf8)

Write-Host "Markdown source documents: $($entries.Count)"
Write-Host "Index: $indexPath"
Write-Host "Bundle: $bundlePath"
